# Generated by Django 4.1 on 2022-10-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_todo_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="task",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
